### ISSUE TITLE
Fails to reload when non-bundled files are changed

### ISSUE THREAD

**Issue by jasonkuhrt** [brunch/auto-reload-brunch#12]
Use-cases where we need to auto-reload even if the file is not part of the final bundle (I'm sure there are more):
- stylus: `@import _non-compiled`
- jade: `include partial`

If `_non-compiled.styl` or `partial.jade` are changed, the browser never knows about it. The work around is terrible:
1. Find & open the file `include`ing or `import`ing the file you just edited
2. Save it
3. Close it
4. go back to your task
5. ^ back to 1

**Comment by dnalot** [comment]
Possible regression? Not working for me with `jaded-brunch`.

**Comment by es128** [comment]
`jaded-brunch` has a known issue with the statically-compiled files because they bypass the normal Brunch pipeline. It should work if you're compiling your templates to javascript. See brunch/brunch#916

**Comment by dnalot** [comment]
Thanks!

**Comment by dnalot** [comment]
monokrome/jaded-brunch#10

**Comment by devinus** [comment]
Guys, it seems that the watcher still ignores files that begin with an underscore `_`. Is there any workaround for htis?

**Comment by es128** [comment]
If you're trying to include an underscore-prefixed file directly, you need to customize your [conventions.ignored setting](https://github.com/brunch/brunch/blob/master/docs/config.md#conventions) in brunch-config.

If it is included in another file (through something like an `@import` statement) then it should work. If you're having trouble with that please describe the details more thoroughly in a new issue.

**Comment by devinus** [comment]
@es128 Is it up to the plugin to make it work through e.g. an `@import` statement? I'm the author of my own plugin that I use to author.

**Comment by es128** [comment]
@devinus yes it is up to the plugin to define a `getDependencies` method to make this work. 

Many brunch plugins use my progeny module to handle this easily.
