### ISSUE TITLE
How do I run auto-reload-brunch on a secure wss rather than http

### ISSUE THREAD

**Issue by reduxdj** [brunch/auto-reload-brunch#45]
thanks

**Comment by Fohlen** [comment]
This is a quiet unsatisfying solution, I must say. Given that modules such as 

- https://www.npmjs.com/package/self-signed-tls-cert-generator

exist, it would be as easy as adding

- a setting to the config
- generating `if_enabled`
- hook into https://github.com/brunch/auto-reload-brunch/blob/master/index.js#L61
