### ISSUE TITLE
[Webkit Browser] refresh in 2 time

### ISSUE THREAD

**Issue by alborq** [brunch/auto-reload-brunch#77]
Hello, 
When i use browser based on webkit (Chrome/Opera) On Windows (Seven/10) tested. 
Content is refresh with 1 time of retard, 
Explain : 
- Start with text '1'
- Display 1
- Edit text to '2'
- Display 1
- Edit text to '1'
- Display 2 

Need 2 Refresh to show good data. 
Delay change nothing set to 5s (5000ms) give same result. 
Work perfectly on Firefox. 

Config : 
OS : 7/10
Node : 4.6.1 
auto-reload-brunch : "auto-reload-brunch": "^2.7.1",
Brownser tested : Firefox|Chrome|Opera : Lastest 

Ask more information if needed.

**Comment by denysdovhan** [comment]
Hi, @alborq!

**Comment by pejalo** [comment]
I'm experiencing this exact issue, on Opera 43 on macOS 10.12.3

All I did was run these commands:
```
brunch new -s marionettejs
npm install --save-dev auto-reload-brunch
npm start
```
